FROM ghcr.io/cross-rs/x86_64-unknown-freebsd:edge

RUN apt-get update \
  && apt-get install -y --no-install-recommends \
  autoconf \
  automake \
  binutils \
  ca-certificates \
  clang-12 \
  curl \
  file \
  gcc \
  git \
  libclang-12-dev \
  libtool \
  llvm-dev \
  m4 \
  make \
  protobuf-compiler \
  python3 \
  python3 \
  python3-pip \
  uuid-runtime
